# Site settings
title: DevRel Collective
email: team@devrelcollective.fun
url: https://devrelcollective.github.io
description: "DevRel Collective ðŸ¥‘- and So Can You! exists to facilitate sharing information, resources, and encouragement among the Developer Relations community."

# Contact form: comment the line below if you want to stick with the default PHP contact form
# contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings -- these are titles of the section
footer:
  copyright: DevRel Collective ðŸ¥‘
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: http://devrelcollective.slack.com
  - title: github
    url: http://github.com/devrelcollective
  - title: twitter
    url: https://twitter.com/pinkyswearing/lists/developer-evangelists


# Postal address (add as many lines as necessary)
address:
  - line: The closest airport to
  - line: San Francisco, CA (<a href="https://twitter.com/mary_grace">Mary</a>)
  - line: Minneapolis, MN (<a href="https://twitter.com/mbbroberg">Matt</a>)
  - line: Wherever (<a href="https://twitter.com/DaveJosephsen">Dave</a>) is
  - line: San Jose, CA (<a href="https://twitter.com/skpodila">Swarna</a>)
  - line: Kansas City, KS (<a href="https://twitter.com/IAmJerdog">Jeremy</a>)

# Credits content
credits: 'Our collective is an inclusive thought experiment started by Dave Josephsen. This site is build by <a href="https://twitter.com/mbbroberg">Matt Broberg</a> on Freelancer: a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# plugins
#plugins:
